local setup = require("lsp.setup")

setup("pylsp")
setup("clangd")
setup("sqlls")
setup("dartls")
setup("dockerls")
setup("vimls")
setup("intelephense")
setup("yamlls")
setup("texlab")
setup("tailwindcss")
setup("gdscript")
